project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('educate.urls')),
    path('admin/', admin.site.urls),
]

urls.py
from django.urls import path, include
from . import views

# account закончить
# signup, register pages and views


app_name = 'educate'

urlpatterns = [
    path('index', views.index, name = 'index'),
    path('courses', views.courses, name = 'courses'),
    path('courses/<int:course_id>', views.lists, name = 'lists'),
    path('courses/course/<int:article_id>', views.article, name = 'article'),
    path('index/about_us', views.about_us, name='about_us'),
    path('index/faq', views.faq, name='faq'),
    path('index/search_page', views.search_page, name='search_page'),
    path('index/signin', views.signin_page, name='signin_page'),
    path('index/signup', views.signup_page, name="signup_page"),
    path('index/register', views.register, name="register"),
    path('index/auth_log', views.auth_log, name="auth_log"),
    path('index/log_out', views.log_out, name="log_out"),
    path('courses/course/<int:article_id>/comment', views.comment, name='comment'),

]

models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Statistic(models.Model):
    page_name = models.CharField(max_length=100, default='index')
    number_of_clicks = models.IntegerField(default=0)

    def __str__(self):
        return 'Number of clicks of ' + self.page_name + ': ' + str(self.number_of_clicks)

class Course(models.Model):
    course_name = models.CharField(max_length=1000)

    def __str__(self):
        return self.course_name

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    DOR = models.DateField(default=timezone.now())
    author_qualification = models.TextField(max_length=500)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

class Article(models.Model):
    article_name = models.CharField(max_length=1000)
    article_text = models.TextField(default="")
    article_date = models.DateField('date published')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.article_name

class Comment(models.Model):
    comment_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment_author = models.CharField(max_length=1000)
    comment_email = models.CharField(max_length=1000)
    comment_date = models.DateField(default=timezone.now())
    comment_text = models.TextField(default='')

    def __str__(self):
        return self.comment_article.article_name + ' ' + self.comment_author

views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login, authenticate, logout
# Models import
from .models import *

def index(request):
    page = Statistic.objects.get(page_name='index')
    page.number_of_clicks+=1
    page.save()
    recent_articles = Article.objects.order_by("-article_date")[:5]
    return render(request, "educate/index.html", {"recent_articles": recent_articles,})

def courses(request):
    all_courses = Course.objects.all()
    return render(request, "educate/courses.html", {"all_courses":all_courses,})

def lists(request, course_id):
    all_articles_by_course = Article.objects.filter(course_id=course_id)
    return render(request, "educate/list.html", {"all_articles_by_course":all_articles_by_course,})

def article(request, article_id):
    exact_article = get_object_or_404(Article, id=article_id)
    comments = Comment.objects.filter(comment_article=article_id)
    comments_number = Comment.objects.filter(comment_article=article_id).count()
    return render(request, "educate/article.html", {"exact_article":exact_article, 'comments':comments, 'comments_number':comments_number,})

def about_us(request):
    teacher_number = Author.objects.all().count()
    click_number = Statistic.objects.get(page_name='index').number_of_clicks
    article_number = Article.objects.all().count()
    course_number = Course.objects.all().count()
    return render(request, "educate/about_us.html", {'teacher_number':teacher_number, 'click_number':click_number, 'article_number':article_number, 'course_number':course_number,})

def faq(request):
    return render(request, "educate/faq.html", {})

## def search_page is not ready!
def search_page(request):
    return

def signup_page(request):
    return render(request, "educate/signup.html", {})


def register(request):
    if request.method == 'POST':
        new_user = User(username=request.POST['username'],
                        password=request.POST['psw'],
                        first_name=request.POST['firstname'],
                        last_name=request.POST['lastname'])
        temp_user = User.objects.filter(username=new_user.username)
        if temp_user:
            return render(request, 'educate/signup.html', {'is_used_username':True, 'is_registred':False, 'is_password_failed':False})
        else:
            val_num = None
            try:
                val_num = validate_password(password=new_user.password, user=new_user, password_validators=None)
                new_user.save()
                new_author = Author(user=new_user, DOR='2000-05-02', author_qualification="")
                new_author.save()
                __set_params__(new_user)
                return render(request, 'educate/signup.html', {'is_used_username':False, 'is_registred':True, 'is_password_failed':False})
            except ValidationError:
                return render(request, 'educate/signup.html', {'is_used_username':False, 'is_registred':False, 'is_password_failed':True})
            except:
                return render(request, 'educate/signup.html', {'is_used_username':False, 'is_registred':False, 'is_password_failed':False})

# hashing the password and adding to the group 'Teachers'
def __set_params__(author):
    group = Group.objects.get(name='Teachers')
    author.groups.add(group)
    author.password = make_password(author.password, salt=None, hasher='default')
    author.save()
    return

def signin_page(request):
    return render(request, "educate/login.html", {})

# incomplete
def auth_log(request):
    username = request.POST['username']
    password = request.POST['psw']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponse(request.user.is_authenticated)
    else:
        return render(request, 'educate/login.html', {'errors':True})

    return


def log_out(request):
    logout(request)
    return

# incomplete
def comment(request, article_id):
    if request.method == "POST":
        author = request.POST['name']
        email = request.POST['email']
        if not author or email:
            return HttpResponse('Bad')
        else:
            text = request.POST['comment_text']
            com = Comment(comment_article=article_id,
                                comment_author=author,
                                comment_email=email,
                                comment_text=text)
            com.save()
            return HttpResponse('Good')

templates/educate/article.html
{% extends 'educate/layout.html' %}

{% block main %}
    <main id="main" class="site-main">
        <section class="site-section-small section-blog-post">

            <div class="container">

                <div class="text-center">
                    <h1 class="section-title-big">Article</h1>
                </div><!-- /.text-center -->

                <ol class="breadcrumb">
                    <li><a href="{% url 'educate:index' %}">Home</a></li>
                    <li><a href="{% url 'educate:courses' %}">Courese</a></li>
                    <li><a href="{% url 'educate:lists' exact_article.id %}">List of Articles</a></li>
                    <li class="active">Article</li>
                </ol><!-- /.breadcrumb -->

                <div class="row">

                    <div class="col-md-9">

                        <div class="row">

                            <div class="col-md-12">

                                <img class="img-carousel post-img" src="../../static/educate/img/portfolio-1.jpg" alt="latest-news-1">

                                <div class="post-content">

                                    <h2 class="post-title">{{ exact_article.article_name }}</h2>
                                    <ul class="post-meta list-unstyled">
                                        <li><a href="{% url 'educate:lists' exact_article.course.id %}">{{ exact_article.course }}</a></li>
                                        <li>{{ exact_article.article_date }}</li>
                                        <!-- <li><a href="#Comments">15 Comments</a></li> -->
                                    </ul><!-- /.post-meta -->

                                    <p class="section-text">{{ exact_article.article_text }}</p>
                                </div><!-- /.post-content -->

                                <div class="post-information">

                                    <img class="img-carousel" src="../../static/educate/img/employee-1.jpg" alt="">

                                    <div class="post-information-content">

                                        <p class="post-author-name">{{ exact_article.author }}</p>
                                        <p class="post-author-position">{{ exact_article.author.author_qualification }}</p>
                                    </div><!-- /.post-information-content -->

                                </div><!-- /.post-information -->

                                <div id="Comments" class="post-comments">

                                    <h3>{{ comments_number }} Comments</h3>
                                      {% if comments %}
                                        {% for comment in comments %}
                                          <div class="post-comment">
                                              <img class="img-carousel" src="../../static/educate/img/employee-3.jpg" alt="">

                                              <div class="post-comment-content">

                                                  <p class="post-comment-author-name">{{ comment.comment_author }}</p>
                                                  <p class="post-comment-date">{{ comment.comment_date }}</p>
                                                  <p class="comment">{{ comment.comment_text }}</p>

                                              </div><!-- /.post-comment-content -->

                                          </div><!-- /.post-comment -->
                                        {% endfor %}
                                      {% endif %}

                                    <div class="leave-comment">

                                        <h3>Leave a comment</h3>

                                        <form class="form-horizontal" method='POST' action="% url 'educate:comment' exact_article.id %">

                                            <div class="row">

                                                <div class="col-sm-6">
                                                    <input class="form-control" type="text" name="name" required placeholder="Name *">
                                                </div>
                                                <div class="col-sm-6">
                                                    <input class="form-control" type="email" name="email" required placeholder="Email *">
                                                </div>
                                                <div class="col-sm-12">
                                                    <textarea class="form-control" placeholder="Comment" name="comment_text"></textarea>
                                                </div>
                                                <div class="col-sm-12 text-right">
                                                    <button type="submit" class="btn btn-medium btn-yellow">Post Comment</button>
                                                </div>

                                            </div>

                                        </form>

                                    </div><!-- /.leave-comment -->

                                </div><!-- /.post-comments -->

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </section><!-- /.section-blog-post -->

    </main><!-- /.site-main -->

{% endblock main %}

templates/educate/index.html
{% extends "educate/layout.html" %}

{% block main %}
<div class="hero background-overlay">

    <div class="hero-text">
        <h1>Simplicity is the soul of efficiency</h1>
    </div> <!-- /.hero-text -->
    <div class="hero-arrow">
        <a class="scrollTo" href="#"><i class="fa fa-angle-down" aria-hidden="true"></i></a>
    </div><!-- /.hero-arrow -->

</div><!-- /.hero -->

<main id="main" class="site-main">

    <section class="site-section section-quote text-center">

        <div class="container">

            <p class="quote">I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite</p>
            <p class="quote-owner yellow-text">G. K. Chesterton</p>

        </div>

    </section><!-- /.section-quote -->

    <section class="site-section section-works light-gray-bg text-center">

        <div class="container">

            <h2 class="section-title">Recent Articles</h2>
            <p class="section-text">We are in the way of success.</p>
            <div class="multi-item-controls">
                <a class="left btn carousel-control" href="#threeSlidesSlider" data-slide="next"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
                <a class="right btn carousel-control" href="#threeSlidesSlider" data-slide="prev"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
        </div>
  <div class="container-fluid">

    <div class="row">

                <div class="col-md-12">

                    <div class="carousel three-slides-slider multi-item-carousel slide" id="threeSlidesSlider">
                        <div class="carousel-inner">
                            <div class="item active">
                                <div class="col-xs-6 col-sm-4">
                                    <a href="{% url 'educate:courses' %}"><img src="static/educate/img/contact.jpg" alt="" class="img-carousel">First one</a>
                                </div>
                            </div><!-- /.item -->
                            <div class="item">
                                <div class="col-xs-6 col-sm-4">
                                    <img src="static/educate/img/employee-5.jpg" alt="" class="img-carousel">
                                </div>
                            </div><!-- /.item -->
                            <div class="item">
                                <div class="col-xs-6 col-sm-4">
                                    <img src="static/educate/img/portfolio-1.jpg" alt="" class="img-carousel">
                                </div>
                            </div><!-- /.item -->
                            <div class="item">
                                <div class="col-xs-6 col-sm-4">
                                    <img src="static/educate/img/slider-3.jpg" alt="" class="img-carousel">
                                </div>
                            </div><!-- /.item -->
                        </div><!-- /.carousel-inner -->
                    </div><!-- /.multi-item-carousel -->

                </div>

            </div>

        </div>

    </section><!-- /.section-works -->

    <section class="site-section-small section-work-with-us yellow-bg text-center">

        <div class="container">

            <p class="section-title-small white-text mb-50">Coming together is a beginning, keeping together is progress, working together is success.</p>
            <a class="btn" href="{% url 'educate:signup_page' %}">Start Now</a>

        </div>

    </section><!-- /.section-work-with-us -->

    <section class="social-networks">

        <div class="container-fluid">

            <div class="row">

                <a class="white-text black-bg twitter-bg" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a class="white-text gray-bg facebook-bg" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a class="white-text black-bg google-plus-bg" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                <a class="white-text gray-bg message-bg" href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>

            </div>

        </div>

    </section><!-- /.social-networks -->
</main><!-- /.site-main -->
{% endblock %}

templates/educate/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Home | MeGaBai</title>

    <meta name="description" content="MeGaBai Team">
    <meta name="author" content="Milan Savov">
    <meta name="keywords" content="Django, project">

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- Loading static -->
    {% load static %}

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- Favicon
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="../../static/educate/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../../static/educate/img/favicon.png">

    <!-- Stylesheets
    ================================================== -->
    <!-- Bootstrap core CSS -->
    <link href="../../static/educate/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../static/educate/css/register.css" rel="stylesheet">
    <link href="../../static/educate/css/style.css" rel="stylesheet">
    <link href="../../static/educate/css/responsive.css" rel="stylesheet">
    <link href="../../static/educate/css/colors.css" rel="stylesheet">
    <link rel="stylesheet" href="../../static/educate/css/faq_style.css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <header id="masthead" class="site-header" data-anchor-target=".hero" data-top="background: rgba(59,58,54,0); border-bottom-color: rgba(226,226,226,0);" data-top-bottom="background: rgba(59,58,54,1); border-bottom-color: rgba(226,226,226,1);">

        <nav id="primary-navigation" class="site-navigation">

            <div class="container-fluid">

                <div class="navbar-header">

                    <a href="{% url 'educate:index' %}" class="site-title yellow-text">Educational<span class="white-text">Portal</span></a>

                </div><!-- /.navbar-header -->

                <div class="main-menu" id="perfect-navbar-collapse">

                    <ul class="nav navbar-nav navbar-right">

                        <li class="active"><a href="{% url 'educate:index' %}">Home</a></li>
                        <li><a href="{% url 'educate:courses' %}">Courses</a></li>
                        <li><a href="{% url 'educate:about_us' %}">About Us</a></li>
                        <li><a href="{% url 'educate:faq' %}">FAQ</a></li>
                        <li><a href="{% url 'educate:search_page' %}">Search</a></li>
                        <li><a href="{% url 'educate:signin_page' %}">Sign in</a></li>
                        <li><a href="{% url 'educate:signup_page' %}">Sign up</a></li>

                    </ul><!-- /.navbar-nav -->

                </div><!-- /.navbar-collapse -->

            </div>

        </nav><!-- /.site-navigation -->

    </header><!-- /#masthead -->



    {% block main %} {% endblock %}

    <footer id="colophon" class="site-footer">

        <div class="container">

            <div class="email">
                <a href="mailto:admin@megabai.com">admin@megabai.com</a>
            </div><!-- /.email -->

            <div class="row">

                <div class="col-md-3 col-xs-6">

                    <div class="mb-xs-20">
                        <a href="{% url 'educate:index' %}" class="site-title yellow-text">Educational<span>Portal</span></a>
                        <p class="mb-0">This is redundant information</p>
                    </div>

                </div>

                <div class="col-md-3 col-xs-6">

                    <div class="mb-xs-20">
                        <h4 class="small-title">Get in touch</h4>
                        <ul class="list-unstyled">
                            <li>Phone: <a href="tel:+15417543010">+1-541-754-3010</a></li>
                            <li>Email: <a href="mailto:admin@megabai.com">admin@megabai.com</a></li>
                            <li>Fax: <a href="tel:+15417543010">+1-541-754-3010</a></li>
                        </ul>
                    </div>

                </div>

                <div class="col-md-3 col-xs-6">

                    <div class="mb-xs-20">
                        <h4 class="small-title">Links</h4>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'educate:about_us' %}">About Us</a></li>
                            <li><a href="{% url 'educate:faq' %}">FAQ</a></li>
                        </ul>
                    </div>

                </div>

                <div class="col-md-3 col-xs-6">

                    <div class="mb-xs-20">
                        <h4 class="small-title">Location</h4>
                        <ul class="list-unstyled">
                            <li>Zhandosova, 37</li>
                            <li>Almaty</li>
                        </ul>
                    </div>

                </div>

            </div>

        </div>

        <div class="copyright">
            <p>&copy; 2019 Educational Portal | Made by <a href="http://" class="yellow-text">MeGaBai</a></p>
        </div><!-- /.copyright -->

    </footer><!-- /.site-footer -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="../../static/educate/js/bootstrap.min.js"></script>
    <script src="../../static/educate/js/jquery.slicknav.min.js"></script>
    <script src="../../static/educate/js/slick.min.js"></script>
    <script src="../../static/educate/js/touchswipe.min.js"></script>
    <script src="../../static/educate/js/skrollr.min.js"></script>
    <script src="../../static/educate/js/jquery.countTo.min.js"></script>
    <script src="../../static/educate/js/script.js"></script>

</body>
</html>

templates/educate/list.html
{% extends "educate/layout.html" %}

{% block main %}
    <main id="main" class="site-main">
        <section class="site-section-small section-blog">

            <div class="container">

                <div class="text-center">

                    <h1 class="section-title-big">List of Articles</h1>
                    <p class="section-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

                </div>

                <ol class="breadcrumb">
                    <li><a href="{% url 'educate:index' %}">Home</a></li>
                    <li><a href="{% url 'educate:courses' %}">Courses</a></li>
                    <li class="active">List of Articles</li>
                </ol><!-- /.breadcrumb -->

                <div class="row">

                    <div class="col-md-9">
                      {% if all_articles_by_course %}
                        {% for article in all_articles_by_course %}
                          <div class="blog-post">
                              <div class="post-content">

                                  <h3><a class="post-title" href="{% url 'educate:article' article.id %}">{{ article.article_name }}</a></h3>
                                  <ul class="post-meta list-unstyled">
                                      <li>{{ article.article_date }}</li>
                                      <!-- <li><a href="blog-post.html#Comments">2 Comments</a></li> -->
                                  </ul><!-- /.post-meta -->
                              </div><!-- /.post-content -->

                          </div><!-- /.blog-post -->
                        {% endfor %}
                      {% endif %}



                        <!-- <div class="text-center">
                            <ul class="pagination">
                                <li><a href="#"><<</a></li>
                                <li class="active"><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">></a></li>
                                <li><a href="#">>></a></li>
                            </ul><!-- /.pagination -->
                        <!-- </div><!-- /.text-center -->

                    </div>

                    <aside class="col-md-3">

                        <div class="sidebar">

                            <div class="widget search-form">
                                <form>
                                    <input class="form-control" type="search" placeholder="Search">
                                    <button type="submit">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </form>
                            </div><!-- /.search-form -->

                            <div class="widget widget-latest-posts">
                                <h4 class="widget-title">Latest Articles</h4>

                                <ul class="list-unstyled posts-list">
                                    <li>
                                        <a href="blog-post.html">
                                            <div class="widget-thumb">
                                                <img class="img-carousel" src="../../static/educate/img/portfolio-7.jpg" alt="">
                                            </div>
                                            <div class="widget-post-info">
                                                <h4 class="widget-post-title">Business Perfect is the best Free Theme</h4>
                                                <p class="widget-post-date">Sep 25, 2015</p>
                                            </div><!-- /.widget-post-info -->
                                        </a>
                                    </li><!-- /.latest-post -->

                                    <li>
                                        <a href="blog-post.html">
                                            <div class="widget-thumb">
                                                <img class="img-carousel" src="../../static/educate/img/portfolio-8.jpg" alt="">
                                            </div>
                                            <div class="widget-post-info">
                                                <h4 class="widget-post-title">We provide unique solutions</h4>
                                                <p class="widget-post-date">Sep 23, 2015</p>
                                            </div><!-- /.widget-post-info -->

                                        </a>
                                    </li><!-- /.latest-post -->

                                    <li>
                                        <a href="blog-post.html">
                                            <div class="widget-thumb">
                                                <img class="img-carousel" src="../../static/educate/img/portfolio-9.jpg" alt="">
                                            </div>
                                            <div class="widget-post-info">
                                                <h4 class="widget-post-title">We are creative minds</h4>
                                                <p class="widget-post-date">Sep 22, 2015</p>
                                            </div><!-- /.widget-post-info -->
                                        </a>
                                    </li><!-- /.latest-post -->
                                </ul>
                            </div><!-- /.widget-latest-posts -->

                        </div><!-- /.sidebar -->

                    </aside>

                </div>

            </div>

        </section><!-- /.section-blog -->
    </main><!-- /.site-main -->

{% endblock main %}

templates/educate/login.html
<!-- Please, call view 'authorize' on this page with password encryption -->
<!-- Password encryption is made by javascript (tokens) -->

{% extends 'educate/layout.html' %}

{% block main %}
<br><br><br>
<form method="POST" action="{% url 'educate:auth_log' %}">
  {% csrf_token %}
  <div class="container">
    {% if errors %}
      <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <label for="username"><b>Username</b></label>
    <input type="text" placeholder="Enter username" name="username" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
    <hr>
    <button type="submit" class="registerbtn">Sign in</button>
  </div>
</form>
{% endblock main %}